CREATE TABLE IF NOT EXISTS WALLETS (
"WALLET_ID" UUID PRIMARY KEY, FULL_NAME VARCHAR(128), TAX_NUMBER VARCHAR(14) UNIQUE, EMAIL VARCHAR(254) UNIQUE, "PASSWORD" VARCHAR(128), "WALLET_ROLE" VARCHAR(12) CHECK ("WALLET_ROLE" IN ('COMMON', 'SHOPKEEPER')) , BALANCE DECIMAL(10, 2), "VERSION" BIGINT
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
"TRANSACTION_ID" UUID PRIMARY KEY, PAYER UUID, PAYEE UUID, "VALUE" DECIMAL(10, 2), CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (PAYER) REFERENCES WALLETS ("WALLET_ID"), FOREIGN KEY (PAYEE) REFERENCES WALLETS ("WALLET_ID")
);